class Cxusage < Formula
  # Placeholder formula - will be auto-generated by the cxusage release workflow.
  # Do not edit by hand; the workflow writes a versioned, sha256-pinned formula here.

  desc "Codex CLI usage tracker with live dashboard"
  homepage "https://github.com/johanneserhardt/cxusage"
  version "0.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://example.invalid/cxusage-darwin-amd64", using: :nounzip
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_arm do
      url "https://example.invalid/cxusage-darwin-arm64", using: :nounzip
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  on_linux do
    on_intel do
      url "https://example.invalid/cxusage-linux-amd64", using: :nounzip
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_arm do
      url "https://example.invalid/cxusage-linux-arm64", using: :nounzip
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  def install
    # This is a no-op placeholder; the real formula installs the staged binary.
    odie "cxusage tap is not yet initialized. Try again after the next tagged release."
  end

  test do
    # Placeholder test; replaced by workflow
    system "true"
  end
end
